/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/Classes/Class.java to edit this template
 */
package GUI;

import BLL.KhoaThi_BLL;
import BLL.PhongThi_BLL;
import DTO.KhoaThi_DTO;
import DTO.PhongThi_DTO;
import DTO.SapXepPhongThi_DTO;
import DTO.ThiSinh_DTO;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;

public class SapXepPhongThi extends javax.swing.JFrame {

    KhoaThi_BLL kb = new KhoaThi_BLL();
    PhongThi_BLL pb = new PhongThi_BLL();
    DefaultTableModel model = new DefaultTableModel();
    DefaultTableModel model2 = new DefaultTableModel();
    public SapXepPhongThi() {
        initComponents();
        setLocationRelativeTo(null);
        setResizable(false);
        model = (DefaultTableModel) tblDSTS.getModel();
        model2 = (DefaultTableModel) tblTSChuaCoPT.getModel();
        setComboKhoaThi();
        loadTSChuaCoPT();
        setTitle("Sắp xếp phòng thi");
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel8 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblTSChuaCoPT = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblDSTS = new javax.swing.JTable();
        cbKhoaThi = new javax.swing.JComboBox<>();
        cbDSPT = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowFocusListener(new java.awt.event.WindowFocusListener() {
            public void windowGainedFocus(java.awt.event.WindowEvent evt) {
                formWindowGainedFocus(evt);
            }
            public void windowLostFocus(java.awt.event.WindowEvent evt) {
            }
        });

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/icons8-back-96 (1).png"))); // NOI18N
        jLabel8.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel8MousePressed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 153, 204));
        jLabel4.setText("SẮP XẾP PHÒNG THI");

        tblTSChuaCoPT.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã thí Sinh", "Họ tên", "Trình độ"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblTSChuaCoPT.setRowHeight(30);
        tblTSChuaCoPT.setShowGrid(true);
        tblTSChuaCoPT.setShowVerticalLines(false);
        tblTSChuaCoPT.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(tblTSChuaCoPT);
        if (tblTSChuaCoPT.getColumnModel().getColumnCount() > 0) {
            tblTSChuaCoPT.getColumnModel().getColumn(0).setPreferredWidth(30);
            tblTSChuaCoPT.getColumnModel().getColumn(2).setPreferredWidth(30);
        }

        tblDSTS.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "STT", "Mã thí sinh", "SBD", "Họ", "Tên"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblDSTS.setRowHeight(30);
        tblDSTS.setShowGrid(true);
        tblDSTS.setShowVerticalLines(false);
        tblDSTS.getTableHeader().setReorderingAllowed(false);
        jScrollPane2.setViewportView(tblDSTS);

        cbKhoaThi.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--Chọn khóa thi--" }));
        cbKhoaThi.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbKhoaThiItemStateChanged(evt);
            }
        });

        cbDSPT.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--Danh sách phòng thi--" }));
        cbDSPT.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbDSPTItemStateChanged(evt);
            }
        });

        jButton1.setText("Sắp xếp phòng thi");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(cbKhoaThi, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(cbDSPT, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 588, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(33, 33, 33)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 342, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton1))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addGap(309, 309, 309)
                        .addComponent(jLabel4)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(jLabel4)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(cbDSPT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbKhoaThi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel8MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MousePressed
        new Home().setVisible(true);
        dispose();
    }//GEN-LAST:event_jLabel8MousePressed

    private void cbKhoaThiItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbKhoaThiItemStateChanged
        if(!cbKhoaThi.getSelectedItem().equals("--Chọn khóa thi--")){
            int idkt = Integer.parseInt(String.valueOf(cbKhoaThi.getSelectedItem()).split(":")[0]);
            setDSPT(idkt);

        }else{
            cbDSPT.removeAllItems();
            cbDSPT.addItem("--Danh sách phòng thi--");
        }
        
    }//GEN-LAST:event_cbKhoaThiItemStateChanged

    private void cbDSPTItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbDSPTItemStateChanged
        if(cbDSPT.getSelectedItem()!=null){
            if(!cbDSPT.getSelectedItem().equals("--Danh sách phòng thi--")){
            int idpt = Integer.parseInt(String.valueOf(cbDSPT.getSelectedItem()).split(":")[0]);
            setDSTS(idpt);

        }else{
            model.setRowCount(0);
        }
        }
        
    }//GEN-LAST:event_cbDSPTItemStateChanged

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        new popupXepPT().setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void formWindowGainedFocus(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowGainedFocus
        loadTSChuaCoPT();
    }//GEN-LAST:event_formWindowGainedFocus
    public void setDSTS(int idpt){
        model.setRowCount(0);
        ArrayList<SapXepPhongThi_DTO> list = pb.getDSTS(idpt);
        int i=1;
        for(SapXepPhongThi_DTO s : list){
            model.addRow(new Object[]{i,s.getIdts(),s.getSbd(),s.getHo(),s.getTen()});
            i++;
        }
    }
    public void loadTSChuaCoPT(){
        model2.setRowCount(0);
        ArrayList<ThiSinh_DTO> list = pb.DSThiSinh_ChuaCoPhong();
        for(ThiSinh_DTO ts : list){
            model2.addRow(new Object[]{ts.getIDThiSinh(),ts.getHo()+" "+ts.getTen(),ts.getTrinhDo()});
        }
    }
    public void setDSPT(int idkt){
        cbDSPT.removeAllItems();
        cbDSPT.addItem("--Danh sách phòng thi--");
        ArrayList<PhongThi_DTO> list = pb.getDSPhongThi(idkt);
        for(PhongThi_DTO pt : list){
            cbDSPT.addItem(pt.getIDPhongThi()+":"+pt.getTenPhongThi());
        }
    }
    public void setComboKhoaThi() {
        
        try {
            ArrayList<KhoaThi_DTO> list = kb.getAll();
            for (KhoaThi_DTO k : list) {
                cbKhoaThi.addItem(k.getIDKhoaThi() + ":" + k.getTenKhoaThi());
                
            }
        } catch (SQLException ex) {
            Logger.getLogger(PhongThi.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(SapXepPhongThi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(SapXepPhongThi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(SapXepPhongThi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(SapXepPhongThi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new SapXepPhongThi().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cbDSPT;
    private javax.swing.JComboBox<String> cbKhoaThi;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tblDSTS;
    private javax.swing.JTable tblTSChuaCoPT;
    // End of variables declaration//GEN-END:variables
}
